### ISSUE TITLE
Reading suggestions

### ISSUE THREAD

**Issue by robonxt** [xizzhu/Joshua#206]
Hello! Started using your app and really appreciate the simplicity of it. There's a few suggestions I would like to see in future versions (would fork and mod it, but I don't have much experience with Android development).

1. More scaling for font size, perhaps a slider + a user input field that accepts values from 0.1x to 3.0x
2. Font selection. Either download it from a open source font server (I'm thinking Google's fonts) or maybe bundled/user-downloaded. 
3. Color/underline Jesus' words
4. Ability to read verses in paragraphs, not separated by verse (similar to how printed ESV/KJV and other physical Bibles are printed)
5. Have the top left header "BOOK, CHAPTER" be clickable to open up the drawer that currently lists the books + chapters. Probably make it jump to current book+chapter.
6. Add new theme option for matching to system theme (light/dark).

Bugs(?):
1. "The Acts" is just spelled as "Acts". 
2. Default highlight color should be set to yellow instead of none?

Once again, thank you for making this app! I know that many of the suggestions are probably just my preferences, but I feel like they are some that will help others in reading the Bible more naturally.

Godspeed!

**Comment by AnneMurphy1** [comment]
Hello, not sure if this is the right place for requests, but can you please add the Literal Standard Version?  I see it's on a lot of apps like Biblehub and Olive Tree, but I much prefer the interface of your Bible app.  There's a website - lsvbible.com/p/get-lsv.html, and it looks like it's downloadable from there with no permission restrictions. It is available as creative commons.

Thank you so much!
