### ISSUE TITLE
Please add LSV to Bible Reader

### ISSUE THREAD

**Issue by AnneMurphy1** [xizzhu/Joshua#207]
Hello, not sure if this is the right place for requests, but can you please add the Literal Standard Version? I see it's on a lot of apps like Biblehub and Olive Tree, but I much prefer the interface of your Bible app. There's a website - lsvbible.com/p/get-lsv.html, and it looks like it's downloadable from there with no permission restrictions. It is available as creative commons.

Thank you so much!

**Comment by xizzhu** [comment]
Tracked by #215
