### ISSUE TITLE
The current "KJV" is not the original KJV 1611

### ISSUE THREAD

**Issue by Jesus-Christ-Is-God** [xizzhu/Joshua#208]
William Blayney made over 400 changes to the original 1611 King James Holy Bible and his updated corrupted version was published in 1769. There are only 3 places I've found so far that have the original KJV 1611 text online and even still the words are updated English a tad bit. But worse is that there is no single file for the original KJV 1611 text either in original English or with the updated English.

Examples of 2 changes:

Ezekiel 24: 7
1611 to 1768 KJV Bibles:  poured it upon the ground
1769 to 2020 KJV Bibles:  poured it not upon the ground

John 15: 20
1611 to 1768 KJV Bibles:  The servant is not greater than the Lord.
1769 to 2020 KJV Bibles:  The servant is not greater than his lord.

I would like to submit an original 1611 King James Holy Bible with updated English without the 400+ changes including additional words which change meaning. This site has the original text with updated grammer, but unchanged by Blayney's additions:
https://www.kingjamesbibleonline.org/1611-Bible/

I would like to help if I can to compile the text, which I have, into a format necessary for your Bible app which I use regularly. And if I am not preferred to help then I request the original 1611 KJV and not the current mass produced corrupted version.

Thank you Jesus for this app! It's been a blessing!
Jesus blesses you!

Thank you.

**Comment by Jesus-Christ-Is-God** [comment]
I recommend a secondary app with the original 1611 KJV with updated English come stock, it would be a gem that no one else has.

**Comment by xizzhu** [comment]
Tracked by #215
